### ISSUE TITLE
Passwordgenerator broken

### ISSUE THREAD

**Issue by Calciumcarbonate321** [NightZan999/TheImperialGod#22]
# Bug in TheImperialGod
**Describe the Bug**
The password generator isn't working

**Write prerequisites to the bug**
Just running the command triggers the bug
** Self hosted or Public**
Public bot

Also specify when did you download the bot files if it is self hosted. 

** Possible Solution**
If you can think about a possible solution please write it here, otherwise leave it blank and we will attend to you

**Comment by NightZan999** [comment]
I don't know how to fix this, I will test some methods maybe. Before the utils revamp it used to work very well, I will really look into this.

**Comment by NightZan999** [comment]
this somehow doesn't show any errors 😕

**Comment by NightZan999** [comment]
@Calciumcarbonate321 and finally after 20 minutes of debugging I have **figured this error out**

**Comment by NightZan999** [comment]
Check my latest commit which will fix this!
