### ISSUE TITLE
Points System

### ISSUE THREAD

**Issue by NightZan999** [NightZan999/TheImperialGod#36]
This issue acts as a checklist to remind me and @Calciumcarbonate321 how much work we have left 😅. 
```yml
Points:
- Givepoints commands
- Utilities with points
- Make sure bots don't fill up DB
- Have a crown role (most active role) which automatically gives the role to the most active user in every guild every week
- Send owner updates if crown role isn't set
- Finishing touches by adding to help command
- Post crown updates and tell the person who gets the crown
- For every 1min a user sits in a VC they should earn 20 points if the VC isn't the AFK vc. 
- Leaderboard commands
- Info commands that explain this system
```
This would make the help command better by telling people we have more commands ;D, and good levelling bots are hard to find.

**Comment by NightZan999** [comment]
I'm happy to say that we've _almost_ finished everything.
*Sadly, we couldn't finish everything which is where **__you__** come in to place!*

So if we find our progress, it pretty much does everything but the hard parts 😂. 

```diff
Points:
+ Givepoints commands
+ Utilities with points
+ Make sure bots don't fill up DB
+ Info commands that explain this system
+ Finishing touches by adding to help command
- Have a crown role (most active role) which automatically gives the role to the most active user in every guild every week
- Send owner updates if crown role isn't set
- Post crown updates and tell the person who gets the crown
- For every 1min a user sits in a VC they should earn 20 points if the VC isn't the AFK vc. 
- Leaderboard commands
```

**Comment by NightZan999** [comment]
I'd be grateful as the **owner of this epic discord bot, to get some features off the community it has built.**

***So basically, I could've built a leaderboard in a matter of minutes. __But__, I wanted to see how much of the community knows python.***

If you make me a leaderboard + crown commands and a lot more stuff on that (that I actually couldn't make 😳), then I'll make you the head of operations in our support 😉. 

Try it out ***before I start to open VS Code 😏***

# How TO win? 
Simply create a fork of this git repository, clone that onto your PC. 
Then change the files, create new files, do all you want.

Commit your files **your main branch.** And then open a pull request asking to merge your fork into the main repo. 

**I'll look into it very very soon and let you know if it works.**

**Comment by Calciumcarbonate321** [comment]
Why close?
