### ISSUE TITLE
Website load speed

### ISSUE THREAD

**Issue by NightZan999** [NightZan999/TheImperialGod#8]
Corrupt EJS please list alternatives. Needs to be solved in a week.

**Comment by NightZan999** [comment]
# Problem
The real problem is that when you do the <%- include("partials/header.ejs") -%> it puts 2 <br> and <br/> after it. Which is 2 line breaks, which I clearly do not like. The second is that I am pretty sure if we change the backend we can change the frontend of the website. 

# Possible Alternatives
PHP maybe. Need support @superzackx, what would you prefer as an alternative to EJS for front end? NodeJS for the backend, but I need complex authentication for public bot which maybe self hosted. 

Secondly we must stop the GitHub automation with pull requests, they put them into complete section when sometimes we have not approved it. Like @Dragonizedpizza's PR, thankfully we did not have automation at the time. 

## Ideal Choice
I might use PHP for the frontend authentication and use MySQL. for the server side and just to help out with the authentication. Secondly I might use discord hacks for auth, so don't worry about that. Secondly I need a good frontend to render results based on channels. Might use Vanilla JS do to so. 

## Your thoughts
Reply to this to tell me what you think is ideal for this. The website will have to be taken into consideration soon I'm afraid. 
Secondly you can just give me suggestions. I can make the front end quite nice.

**Comment by superzackx** [comment]
We can use the res.sendFile method. Or I can just fix the EJS error. I need access to repl for it. Auth can be done using google sign API or make our own using PHP or passport.js OR cookies.

**Comment by superzackx** [comment]
Okay, got it. You need to remove all body tags and links from the .ejs files. Move all that to the header and footer files. Secondly,  the first thing in your file needs to be <%- include("partials/header.ejs") -%>

**Comment by Dragonizedpizza** [comment]
bruh

**Comment by superzackx** [comment]
Fixed, just clone my repl.

**Comment by NightZan999** [comment]
Link?

**Comment by NightZan999** [comment]
Never mind found it. Will clone

**Comment by NightZan999** [comment]
# Other **alternatives**
@superzackx I checked the repl and saw it, its fine. But fact is the amount of EJS that we are using is not enough. 
See in every file we are using this: `<%-include("./partials/head.ejs")->` which is enough to me that we should switch. 

Secondly I was asking you about an Express Router. We could use that to organize our stylesheets. If you can't figure that out then try this. 
You know NodeJS renders the requests to EJS files. Make that for HTML and SHTML files. Its fine if you do either one, but then we don't have to get to the complexity of using an Express router. 

## Final thoughts
I'd say we switch now and then change back later when we really need it, and the navbar we can just simply copy and paste the source code of it. In the **new revamp of the website** I am adding scrollspy and have configured it to work with Bootstrap 4 and Jquery. 

So it would be great if we could render to HTML files.

**Comment by superzackx** [comment]
we have to use the res.sendFile() method for rendering files.
